name: Node.js CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  test_frontend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.0
      uses: actions/setup-node@v3
      with:
        node-version: 18.0
    - run: |
        cd frontend
        npm ci
        npm run test
